FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install --no-install-recommends sshpass openssh-client -y \
	&& apt-get upgrade -y \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir -r /usr/local/lib/python3.14/site-packages/ansible_collections/azure/azcollection/requirements.txt

COPY 01_devbox_config.yml ./
COPY class.azure_rm.yml ./
COPY wsl_create_user.sh ./
COPY wsl_install_docker.sh ./
COPY wsl_install_gh.sh ./
COPY wsl_install_node.sh ./
COPY wsl_setup_ssh.sh ./

ARG AZURE_PROFILE=AzureCloud
ENV AZURE_PROFILE=${AZURE_PROFILE}

CMD ["sh", "-c", "ansible-playbook 01_devbox_config.yml -i class.azure_rm.yml -k -e ansible_user=$username -e ansible_password=$password -e devbox=tag_type_devbox_$username"]